tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#001a42",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#3980f4",
        "on-primary-fixed": "#131b2e",
        "on-error-container": "#93000a",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004395",
        background: "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed-variant": "#3f465c",
        "primary-fixed": "#dae2fd",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "tertiary-fixed-dim": "#adc6ff",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45464d",
        "secondary-fixed": "#acedff",
        "primary-fixed-dim": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "tertiary-fixed": "#d8e2ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        primary: "#000000",
        "primary-container": "#131b2e",
        tertiary: "#000000",
        "inverse-surface": "#2d3133",
        secondary: "#00687a",
        "outline-variant": "#c6c6cd",
        "inverse-primary": "#bec6e0",
        surface: "#f7f9fb",
        "surface-variant": "#e0e3e5",
        outline: "#76777d",
        "on-background": "#191c1e",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "on-tertiary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-container": "#006172",
        error: "#ba1a1a",
        "surface-tint": "#565e74",
        "surface-dim": "#d8dadc",
        "secondary-container": "#57dffe",
        "surface-container-highest": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "32px",
        "stack-md": "32px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "stack-sm": "16px",
        base: "8px",
        "margin-desktop": "64px",
        "stack-lg": "64px",
      },
      fontFamily: {
        "display-lg-mobile": ["Space Grotesk"],
        "code-md": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "headline-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "label-sm": ["Space Grotesk"],
      },
      fontSize: {
        "display-lg-mobile": [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "code-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-sm": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" },
        ],
      },
    },
  },
};
